<?php

/**
 * @file
 * Homework on topic Files, Libraries, Views.
 */

include_once ('training5_file_lib.pages.inc');
/**
 * Implements hook_menu().
 */
function training5_file_lib_menu() {
  $items['files'] = array(
    'title' => 'Files',
    'page callback' => 'training5_file_lib_files',
    'access callback' => TRUE,
  );
  $items['files/%ctools_js/upload_file'] = array(
    'title' => 'Add file',
    'page callback' => 'training5_file_lib_upload_file',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['files/download/%file'] = array(
    'title' => 'Download file',
    'page callback' => 'training5_file_lib_download',
    'page arguments' => array(2),
    'access callback' => 'training5_file_lib_access_callback',
    'type' => MENU_CALLBACK,
  );
  $items['currency/load'] = array(
    'title' => 'Currency load',
    'page callback' => 'training5_file_lib_batch',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Access callback for downloading files.
 */
function training5_file_lib_access_callback() {
  global $user;
  $query = db_select('file_managed', 'f')
    ->fields('f', array('uid'))
    ->condition('f.uid', $user->uid);
  $result = $query->execute()->rowCount();

  if (!empty($result)) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Implements hook_theme().
 */
function training5_file_lib_theme() {
  $theme['training5_file_lib_theme'] = array(
    'variables' => array(
      'link' => NULL,
    ),
    'template' => 'templates/training5_file_lib_template',
  );

  return $theme;
}

/**
 * Implements hook_views_api().
 */
function training5_file_lib_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'training5_file_lib') . '/includes/views',
  );
}

/**
 * Page callback for currency/load using batch operation.
 */
function training5_file_lib_batch() {
  $batch = array(
    'title' => t('Load currency'),
    'operations' => array(),
    'finished' => 'training5_file_lib_batch_finished',
    'file' => drupal_get_path('module', 'training5_file_lib') . '/training5_file_lib.pages.inc',
  );

  $xml = training5_file_lib_get_xml_data();
  $progress = 0;
  $limit = 5;
  $max = count($xml->Currency);

  $db_result = db_select('training5_file_lib_rates', 'tfl')
    ->fields('tfl')
    ->execute()
    ->fetchCol();

  if (count($db_result) != 0) {
    db_delete('training5_file_lib_rates')->execute();
    while ($progress <= $max) {
      $batch['operations'][] = array(
        'training5_file_lib_batch_callback',
        array($progress, $limit),
      );
      $progress = $progress + $limit;
    }
  }
  else {
    while ($progress <= $max) {
      $batch['operations'][] = array(
        'training5_file_lib_batch_callback',
        array($progress, $limit),
      );
      $progress = $progress + $limit;
    }
  }

  batch_set($batch);
  batch_process('currency/view');
}
